#include "Cunoscut.h"




void Cunoscut::newOperation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-1-15-103-79220c7:15429e4362c:-8000:00000000000008AF begin
{
}
// section 10-1-15-103-79220c7:15429e4362c:-8000:00000000000008AF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cunoscut::newOperation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-1-15-103-79220c7:15429e4362c:-8000:00000000000008B1 begin
{
}
// section 10-1-15-103-79220c7:15429e4362c:-8000:00000000000008B1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
